<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1623226004305' stop='1623226064330'>
    <name>loging to application</name>
    <title>loging to application</title>
    <test-cases>
        <test-case start='1623226004307' status='pending' stop='1623226004307'>
            <name>login by json data </name>
            <title>login by json data </title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Test ignored</message>
                <stack-trace>undefined</stack-trace>
            </failure>
        </test-case>
        <test-case start='1623226004308' status='broken' stop='1623226064324'>
            <name>login by excel data</name>
            <title>login by excel data</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-91.0.4472.77'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "loging to application login by excel data" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\swamynarayan\Desktop\demo_wedriverio\test\specs\loginTest1.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "loging to application login by excel data" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\swamynarayan\Desktop\demo_wedriverio\test\specs\loginTest1.js)
                    at createTimeoutError (C:\Users\swamynarayan\Desktop\demo_wedriverio\node_modules\mocha\lib\errors.js:498:15)
                    at Test.Runnable._timeoutError (C:\Users\swamynarayan\Desktop\demo_wedriverio\node_modules\mocha\lib\runnable.js:431:10)
                    at Timeout.&lt;anonymous> (C:\Users\swamynarayan\Desktop\demo_wedriverio\node_modules\mocha\lib\runnable.js:246:24)
                    at listOnTimeout (internal/timers.js:549:17)
                    at processTimers (internal/timers.js:492:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>